name: Build on master push (amd64 only)

on:
  push:
    branches:
      - master

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build ord image
    runs-on: ubuntu-latest
    env:
      VERSION: v0.5.1
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Show available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform linux/amd64 \
          --build-arg VERSION=$VERSION \
          --tag greerso/ord:$VERSION-amd64 \
          --output "type=registry" .
